Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job               count
--------------  -------
all                   1
compress_fastq        4
fasterq_dump          2
fastp                 2
fastqc                4
featurecounts         1
hisat2_align          2
hisat2_index          1
multiqc               1
prefetch_sra          2
samtools_index        2
samtools_sort         2
total                24

Resources before job selection: {'_cores': 8, '_nodes': 9223372036854775807}
Ready jobs (3)
Select jobs to execute...
Selected jobs (1)
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

[Mon May 26 17:54:46 2025]
rule hisat2_index:
    input: reference/GCF_000484505.2_ASM48450v2_genomic.fna
    output: reference/hisat2_index/genome.1.ht2, reference/hisat2_index/genome.2.ht2, reference/hisat2_index/genome.3.ht2, reference/hisat2_index/genome.4.ht2, reference/hisat2_index/genome.5.ht2, reference/hisat2_index/genome.6.ht2, reference/hisat2_index/genome.7.ht2, reference/hisat2_index/genome.8.ht2
    log: logs/hisat2_index/build.log
    jobid: 4
    reason: Missing output files: reference/hisat2_index/genome.1.ht2, reference/hisat2_index/genome.4.ht2, reference/hisat2_index/genome.6.ht2, reference/hisat2_index/genome.7.ht2, reference/hisat2_index/genome.5.ht2, reference/hisat2_index/genome.2.ht2, reference/hisat2_index/genome.3.ht2, reference/hisat2_index/genome.8.ht2
    threads: 8
    resources: tmpdir=/tmp

mkdir -p $(dirname reference/hisat2_index/genome.1.ht2) && hisat2-build reference/GCF_000484505.2_ASM48450v2_genomic.fna reference/hisat2_index/genome -p 8 > logs/hisat2_index/build.log 2>&1
[Mon May 26 17:54:47 2025]
Finished job 4.
1 of 24 steps (4%) done
Resources before job selection: {'_cores': 8, '_nodes': 9223372036854775807}
Ready jobs (2)
Select jobs to execute...
Selected jobs (2)
Resources after job selection: {'_cores': 6, '_nodes': 9223372036854775805}

[Mon May 26 17:54:47 2025]
rule prefetch_sra:
    output: raw_data/sra/SRR23426209
    log: logs/prefetch/SRR23426209.log
    jobid: 8
    reason: Missing output files: raw_data/sra/SRR23426209
    wildcards: sample=SRR23426209
    resources: tmpdir=/tmp

prefetch SRR23426209 -O raw_data/sra/SRR23426209 > logs/prefetch/SRR23426209.log 2>&1

[Mon May 26 17:54:47 2025]
rule prefetch_sra:
    output: raw_data/sra/SRR23426208
    log: logs/prefetch/SRR23426208.log
    jobid: 15
    reason: Missing output files: raw_data/sra/SRR23426208
    wildcards: sample=SRR23426208
    resources: tmpdir=/tmp

prefetch SRR23426208 -O raw_data/sra/SRR23426208 > logs/prefetch/SRR23426208.log 2>&1
[Mon May 26 17:56:19 2025]
Finished job 15.
2 of 24 steps (8%) done
Resources before job selection: {'_cores': 7, '_nodes': 9223372036854775806}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 3, '_nodes': 9223372036854775805}

[Mon May 26 17:56:19 2025]
rule fasterq_dump:
    input: raw_data/sra/SRR23426208
    output: raw_data/fastq/SRR23426208_1.fastq, raw_data/fastq/SRR23426208_2.fastq
    log: logs/fasterq_dump/SRR23426208.log
    jobid: 14
    reason: Missing output files: raw_data/fastq/SRR23426208_2.fastq, raw_data/fastq/SRR23426208_1.fastq; Input files updated by another job: raw_data/sra/SRR23426208
    wildcards: sample=SRR23426208
    threads: 4
    resources: tmpdir=/tmp

fasterq-dump raw_data/sra/SRR23426208/SRR23426208.sra --threads 4 --outdir $(dirname raw_data/fastq/SRR23426208_1.fastq) > logs/fasterq_dump/SRR23426208.log 2>&1
Full Traceback (most recent call last):
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 117, in __rule_fasterq_dump
    rule fastp:
     ^^^^^^^^^^
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  fasterq-dump raw_data/sra/SRR23426208/SRR23426208.sra --threads 4 --outdir $(dirname raw_data/fastq/SRR23426208_1.fastq) > logs/fasterq_dump/SRR23426208.log 2>&1' returned non-zero exit status 3.

[Mon May 26 17:56:21 2025]
Error in rule fasterq_dump:
    jobid: 14
    input: raw_data/sra/SRR23426208
    output: raw_data/fastq/SRR23426208_1.fastq, raw_data/fastq/SRR23426208_2.fastq
    log: logs/fasterq_dump/SRR23426208.log (check log file(s) for error details)
    conda-env: /home/henri/BifrostOmics/rnaseq_project/.snakemake/conda/7170c09ba895b6e4c9cb60c87660164d_
    shell:
        fasterq-dump raw_data/sra/SRR23426208/SRR23426208.sra --threads 4 --outdir $(dirname raw_data/fastq/SRR23426208_1.fastq) > logs/fasterq_dump/SRR23426208.log 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 117, in __rule_fasterq_dump
    rule fastp:
     ^^^^^^^^^^
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  fasterq-dump raw_data/sra/SRR23426208/SRR23426208.sra --threads 4 --outdir $(dirname raw_data/fastq/SRR23426208_1.fastq) > logs/fasterq_dump/SRR23426208.log 2>&1' returned non-zero exit status 3.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/henri/BifrostOmics/rnaseq_project/Snakefile, line 70:
Command 'set -euo pipefail;  fasterq-dump raw_data/sra/SRR23426208/SRR23426208.sra --threads 4 --outdir $(dirname raw_data/fastq/SRR23426208_1.fastq) > logs/fasterq_dump/SRR23426208.log 2>&1' returned non-zero exit status 3.
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 70, in __rule_fasterq_dump

RuleException:
CalledProcessError in file /home/henri/BifrostOmics/rnaseq_project/Snakefile, line 70:
Command 'set -euo pipefail;  fasterq-dump raw_data/sra/SRR23426208/SRR23426208.sra --threads 4 --outdir $(dirname raw_data/fastq/SRR23426208_1.fastq) > logs/fasterq_dump/SRR23426208.log 2>&1' returned non-zero exit status 3.
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 70, in __rule_fasterq_dump
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Terminating processes on user request, this might take some time.
Full Traceback (most recent call last):
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 78, in __rule_prefetch_sra
    log:
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  prefetch SRR23426209 -O raw_data/sra/SRR23426209 > logs/prefetch/SRR23426209.log 2>&1' returned non-zero exit status 3.

[Mon May 26 17:57:26 2025]
Error in rule prefetch_sra:
    jobid: 8
    output: raw_data/sra/SRR23426209
    log: logs/prefetch/SRR23426209.log (check log file(s) for error details)
    conda-env: /home/henri/BifrostOmics/rnaseq_project/.snakemake/conda/7170c09ba895b6e4c9cb60c87660164d_
    shell:
        prefetch SRR23426209 -O raw_data/sra/SRR23426209 > logs/prefetch/SRR23426209.log 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 78, in __rule_prefetch_sra
    log:
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  prefetch SRR23426209 -O raw_data/sra/SRR23426209 > logs/prefetch/SRR23426209.log 2>&1' returned non-zero exit status 3.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/henri/BifrostOmics/rnaseq_project/Snakefile, line 53:
Command 'set -euo pipefail;  prefetch SRR23426209 -O raw_data/sra/SRR23426209 > logs/prefetch/SRR23426209.log 2>&1' returned non-zero exit status 3.
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 53, in __rule_prefetch_sra

RuleException:
CalledProcessError in file /home/henri/BifrostOmics/rnaseq_project/Snakefile, line 53:
Command 'set -euo pipefail;  prefetch SRR23426209 -O raw_data/sra/SRR23426209 > logs/prefetch/SRR23426209.log 2>&1' returned non-zero exit status 3.
  File "/home/henri/BifrostOmics/rnaseq_project/Snakefile", line 53, in __rule_prefetch_sra
  File "/home/henri/miniconda3/envs/rnaseq_pipeline/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Complete log: .snakemake/log/2025-05-26T175445.652139.snakemake.log
unlocking
removing lock
removing lock
removed all locks
